name: sistem_pertahanan_tubuh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_neumorphic: ^3.2.0
  flutter: 
    sdk: flutter
  url_strategy: ^0.2.0
  flutter_screenutil: ^5.5.3+2

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

